name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libx11-dev

    - name: Run autoreconf
      run: |
        autoreconf -i

    - name: Configure
      run: |
        ./configure

    - name: Build
      run: |
        make

    - name: Run tests
      run: |
        make check
