name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install necessary tools for autoconf
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake libtool

    # Generate configure script
    - name: Generate configure script
      run: autoreconf -i

    # Run configure script
    - name: Configure
      run: ./configure

    # Build the project
    - name: Build
      run: make

    # Run tests
    - name: Run Tests
      run: make check

    # Run distcheck (if necessary)
    - name: Distcheck
      run: make distcheck
